all:
	g++ -std=c++17 Minesweeper.cpp Minesweeper_functions.cpp -o Minesweeper -I /opt/homebrew/Cellar/sfml@2/2.6.2/include -L /opt/homebrew/Cellar/sfml@2/2.6.2/lib -lsfml-graphics -lsfml-window -lsfml-system
